### ISSUE TITLE
Upload Mutation doesn't work with DioLink

### ISSUE THREAD

**Issue by altech7** [TarekkMA/gql_dio_link#5]
I'm using gql_dio_link and graphql_flutter v4 because i need interceptor for manage auth cookie with CookieManager.

I got this error during mutation call for upload file : 
```dart
flutter: *** DioError ***:
flutter: uri: http://localhost:4000/graphql
flutter: DioError [DioErrorType.DEFAULT]: Converting object to an encodable object failed: Instance of 'MultipartFile'
#0      _JsonStringifier.writeObject (dart:convert/json.dart:687:7)
#1      _JsonStringifier.writeMap (dart:convert/json.dart:768:7)
#2      _JsonStringifier.writeJsonValue (dart:convert/json.dart:723:21)
#3      _JsonStringifier.writeObject (dart:convert/json.dart:678:9)
#4      _JsonStringifier.writeMap (dart:convert/json.dart:768:7)
#5      _JsonStringifier.writeJsonValue (dart:convert/json.dart:723:21)
#6      _JsonStringifier.writeObject (dart:convert/json.dart:678:9)
#7      _JsonStringStringifier.printOn (dart:convert/json.dart:876:17)
#8      _JsonStringStringifier.stringify (dart:convert/json.dart:861:5)
#9      JsonEncoder.convert (dart:convert/json.dart:261:30)
#10     JsonCodec.encode (dart:convert/json.dart:171:45)
#11     DefaultTransformer.transformRequest (package:dio/src/transformer.dart:62:21)
#12     DioMixin._transformData (package:dio/src/dio.dart:1014:39)
<…>
```

Here is my graphql client : 
```dart
  final Link link = DioLink(
      '${DotEnv().env['BASE_URL']}/graphql',
      client: httpService.dio,
    );
    client = GraphQLClient(
      cache: GraphQLCache(),
      link: link,
    );
``` 

Mutation : 
```dart
const String uploadFile = """
  mutation uploadRequestedFile(\$requestedFileId: ID!, \$file: Upload!) {
    uploadRequestedFile(requestedFileId: \$requestedFileId, file: \$file) {
      id
      documentUrl
    }
  }
""";
```
```dart
    final QueryResult result = await graphqlService.client.mutate(
      MutationOptions(
        document: gql(uploadFile),
        variables: {
          'file': await imagePickerService.multipartFileFrom(document.file),
          'requestedFileId': document.id,
        },
      ),
    );
```

This problem occurs when serializing the body http.
Therefore i checked HttpLink source code, and here is how httpLink handles this case :
```dart
    final httpBody = _encodeAttempter(
      request,
      (Map body) => json.encode(
        body,
        toEncodable: (dynamic object) =>
            (object is http.MultipartFile) ? null : object.toJson(),
      ),
    )(body);
```

**Comment by chuongdevJC** [comment]
Hi! Did u get solution?

**Comment by TarekkMA** [comment]
This repo is no longer the main repo please refer to gql-dart/gql#169
